import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { StudentAppSidebar } from "@/components/sidebar/student-sidebar";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Dashboard",
	description: "Generated by create next app",
};

export default function DashboardLayout({
	children,
}) {
	return (
			<div
				className={`flex-1 flex flex-col h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<main className='flex-1 overflow-y-auto'>
                    <ThemeProvider attribute="class" defaultTheme="light">
                    <SidebarProvider>
                        <StudentAppSidebar/>
					{children}
					<Toaster position='top-right' />
                    </SidebarProvider>
                    </ThemeProvider>
				</main>
			</div>
	);
}
