import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/sidebar/app-sidebar";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "IT Support",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<ThemeProvider attribute='class' defaultTheme='light'>
			<SidebarProvider>
				<AppSidebar />
				{children}
				<Toaster />
			</SidebarProvider>
		</ThemeProvider>
	);
}
