import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import {SidebarProvider} from "@/components/ui/sidebar";
import {InstructorAppSidebar} from "@/components/sidebar/instructorSidebar";
import {Toaster} from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "instructor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <html lang="en" suppressHydrationWarning>
      <div
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="light">
            <SidebarProvider>
                <InstructorAppSidebar/>
                <Toaster/>
                {children}
            </SidebarProvider>
        </ThemeProvider>
      </div>
    // </html>
  );
}
